### ISSUE TITLE
Question: Can you access a date range

### ISSUE THREAD

**Issue by stratus-ss** [cyberjunky/python-garminconnect#22]
Hi, 

I'm just wondering if there is a way to access a date range of data instead of today(). Obviously, could write a loop of some sort but I didn't know if there was a support built in for extracting say *all* data to extract the historical data with this library

Thanks for the library!

**Comment by zenelba** [comment]
I had the same issue. It works fine with the loop if there are not many days in the data range - the issue is that data retrieval is rather slow...

**Comment by cyberjunky** [comment]
@stratus-ss for which data?

**Comment by mr-devs** [comment]
First of all, thank you very much for making this - it seems to work well and it will definitely be something that I make use of on a regular basis.

That said, I found this issue because I was wondering the same thing. Based on the readme, the only functions that run over a range of dates are: `get_activities_by_date` and `get_body_composition`.

> for which data?

It would be very useful if the user statistics functions could also operate over a range of dates in the same way - i.e., by taking `start_date` and an `end_date`.

**Comment by cyberjunky** [comment]
I would be happy to but I have no working url for that data, the current ones end with daily and are focussed on daily data only.
