### ISSUE TITLE
Challenges/Goals data

### ISSUE THREAD

**Issue by andreasscherbaum** [cyberjunky/python-garminconnect#65]
Is it possible to fetch the challenges and goals data?
That data is shown in the `Challenges` and `Goals` tabs on the Connect website

**Comment by dpupkov** [comment]
You can theoretically grab that info from these API points:

Earned badges - https://connect.garmin.com/modern/proxy/badge-service/badge/earned
Completed AdHoc challenges - https://connect.garmin.com/modern/proxy/adhocchallenge-service/adHocChallenge/historical
Completed Badge Challenges - https://connect.garmin.com/modern/proxy/badgechallenge-service/badgeChallenge/completed?start=1&limit=10000

**Comment by cyberjunky** [comment]
Thanks a lot!
I have added these to version 0.1.42, not sure if get_adhoc_challenges request is correct, response is empty, but maybe that's because I'm not challenged enough ;-) Can you test?

```
    ## Get earned badges for user
    logger.info(api.get_earned_badges())

    ## Get adhoc challenges data from start and limit
    logger.info(api.get_adhoc_challenges(1,100)) # 1=start, 100=limit

    # Get badge challenges data from start and limit
    logger.info(api.get_badge_challenges(1,100)) # 1=start, 100=limit
```

**Comment by aiivers** [comment]
@cyberjunky I'm trying to use the get_adhoc_challenges request but it doesn't seem to work properly. The "players" value is always an empty list, the limit doesn't seem to do anything over 99, and I don't think the API is returning _my_ challenges, just all challenges (since I've now queried about 40k challenges and my script is still going)
Any recommendations on solutions? I'd love to use this to get a running total of challenge winners for me and my friends for our home dashboard
