### ISSUE TITLE
Password reset every week? 

### ISSUE THREAD

**Issue by terterwat** [cyberjunky/python-garminconnect#73]
My garmin password is being reset every week on the same Day. Could that Happen because I am using this api regulary? Any ideas how to prevent this?
Thank you

**Comment by theflyingwombat** [comment]
@terterwat  I had this happen earlier this year when I had too many failed authentications within a short amount of time. It might be due to the 404 unauthorized issue not necessarily a bad password login. I increased the delay to try and log back in and that stopped the password reset emails. I switched from checking for activities from every 5 minutes to checking every hour.
